import "./globals.css";
import type { Metadata } from "next";
import Navbar from "./components/common/Navbar";
import { Kanit } from "next/font/google";

const kanit = Kanit({
  subsets: ['latin'],
  weight: ["400", "600", "800", "900"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${kanit.className} antialiased bg-primary-bg h-[500vh]`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
